[build]
  command = "npm run build --legacy-peer-deps"
  publish = "build"

[build.environment]
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyA_FZyRy_p1QNX0giy53UK3OzGKVXROEFE"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "elysium-ef45c.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "elysium-ef45c"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "elysium-ef45c.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "438129451511"
  REACT_APP_FIREBASE_APP_ID = "1:438129451511:web:2207b9e739b961682b4ef2"
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_FIREBASE_API_KEY,REACT_APP_FIREBASE_APP_ID,REACT_APP_FIREBASE_AUTH_DOMAIN,REACT_APP_FIREBASE_MESSAGING_SENDER_ID,REACT_APP_FIREBASE_PROJECT_ID,REACT_APP_FIREBASE_STORAGE_BUCKET,REACT_APP_HUGGINGFACE_API_KEY,REACT_APP_MISTRAL_API_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200